### get about
@serverUrl = http://192.168.50.117

GET {{serverUrl}}/device/reboot HTTP/1.1

GET {{serverUrl}}/settings/about HTTP/1.1

GET {{serverUrl}}/settings/get HTTP/1.1

GET {{serverUrl}}/settings/clear HTTP/1.1

POST {{serverUrl}}/settings/update
Content-Type: application/json

{
    "device": {
        "name": "atom1",
        "setup_mode": true,
        "admin": "admin",
        "password": "password"
    },
    "wifi": {
        "ssid": "ssid",
        "password": "password"
    }
}
